import json

orig = json.load(open('/Users/abokobza/Downloads/LeaSolBok.github.io-main/actorquiz/packages/avatar/data_he.json'))

# Corrected values based on Hebrew Wikipedia (he.wikipedia.org) pages:
# "אווטאר – דמויות" and "האגדה של קורה – דמויות", and character-specific pages
# (e.g. "אנג (דמות)", "סוקה (דמות)", "קטרה (דמות)", "טוף בייפונג", "אירו (דמות)", "צוקו").
corrections = {
    "aang": "אנג",
    "zuko": "צוקו",
    "katara": "קטרה",
    "sokka": "סוקה",
    "toph beifong": "טוף בייפונג",
    "azula": "אזולה",
    "iroh": "אירו",
    "korra": "קורה",
    "appa": "אפה",
    "momo": "מומו",
    "suki": "סוקי",
    "mai": "מאי",
    "ty lee": "טאי לי",
    "ozai": "אוזאי",
    "roku": "רוקו",
    "kyoshi": "קיושי",
    "tenzin": "טנזן",
    "asami sato": "אסאמי סאטו",
    "bolin": "בולין",
    "mako": "מאקו",
    "amon": "אמון",
    "kuvira": "קובירה",
    "zaheer": "זאהיר",
    "lin beifong": "לין בייפונג",
    "jinora": "ג'ינורה",
    "bumi": "בומי",
    "jet": "ג'ט",
    "combustion man": "איש הבעירה",
    "pabu": "פאבו",
    "naga": "נאגה",
    "aiwei": "אייווי",
    "amak": "אמאק",
    "arnook": "ארנוק",
    "azulon": "אזולון",
    "baatar": "בטאר",
    "baatar jr.": "בטאר ג'וניור",
    "bosco": "בוסקו",
    "bujing": "בוג'ינג",
    "bum-ju": "בום-ג'ו",
    "bumi 2": "בומי 2",
    "butakha": "בוטאקה",
    "butler": "משרת",
    "buttercup raiko": "באטרקאפ רייקו",
    "cabbage merchant": "סוחר כרוב",
    "cam": "קאם",
    "chan": "צ'אן",
    "chanyu": "צ'אניו",
    "chong": "צ'ונג",
    "chow": "צ'או",
    "chung": "צ'ונג",
    "daw": "דאו",
    "desna and eska": "דסנה ואסקה",
    "ding": "דינג",
    "druk": "דרוק",
    "due": "דיו",
    "fang": "פאנג",
    "flopsie": "פלופסי",
    "fong": "פונג",
    "fung": "פונג",
    "ganbat": "גנבט",
    "ghazan": "גאזאן",
    "ginger": "ג'ינג'ר",
    "gombo": "גומבו",
    "gommu": "גומו",
    "governor of yi": "מושל יי",
    "gow": "גאו",
    "gyatso": "ג'יאטסו",
    "hahn": "האן",
    "hakoda": "האקודה",
    "hama": "האמה",
    "haru": "הארו",
    "hawky": "נצי",
    "hide": "הייד",
    "hiroshi sato": "הירושי סאטו",
    "hong li": "הונג לי",
    "hotah": "הוטה",
    "hou-ting": "האו-טינג",
    "hundun": "הונדון",
    "huu": "הו",
    "ikki": "איקי",
    "iroh 2": "אירו 2",
    "izumi": "איזומי",
    "jee": "ג'י",
    "jeong jeong": "ג'ונג ג'ונג",
    "jin": "ג'ין",
    "joo dee": "ג'ו די",
    "kahchi": "קאצ'י",
    "kai": "קאי",
    "kanna": "קנה",
    "karu": "קארו",
    "kay-fon": "קיי-פון",
    "kenji": "קנג'י",
    "koh": "קו",
    "kong": "קונג",
    "kuei": "קואי",
    "kuon": "קוון",
    "kuruk": "קורוק",
    "kwan": "קוואן",
    "kya": "קיה",
    "la": "לה",
    "lao beifong": "לאו בייפונג",
    "lily": "לילי",
    "long feng": "לונג פנג",
    "longshot": "לונגשוט",
    "macmu-ling": "מקמו-לינג",
    "masaru": "מסארו",
    "meelo": "מילו",
    "meng": "מנג",
    "michi": "מיצ'י",
    "ming": "מינג",
    "ming-hua": "מינג-הואה",
    "miyuki": "מיוקי",
    "moku": "מוקו",
    "mongke": "מונגקה",
    "mui": "מוי",
    "mula": "מולה",
    "mung": "מונג",
    "nyla": "ניילה",
    "ogodei": "אוגודיי",
    "oh": "אוה",
    "on ji": "און ג'י",
    "oogi": "אוגי",
    "opal": "אופל",
    "oyaji": "אויאג'י",
    "p li": "פ. לי",
    "pakku": "פאקו",
    "pao": "פאו",
    "pasang": "פסאנג",
    "pathik": "פאטיק",
    "pema": "פמה",
    "piandao": "פיאנדאו",
    "pipsqueak": "פיפסקוויק",
    "poki": "פוקי",
    "pong": "פונג",
    "poon": "פון",
    "poppy beifong": "פופי בייפונג",
    "qin": "צ'ין",
    "qin lee": "צ'ין לי",
    "quon": "קוון",
    "raava": "ראאבה",
    "raiko": "רייקו",
    "rohan": "רוהאן",
    "ruon-jian": "רואון-ג'יאן",
    "ryu": "ריו",
    "saikhan": "סאיקאן",
    "sangok": "סנגוק",
    "sela": "סלה",
    "senna": "סנה",
    "sha-mo": "שה-מו",
    "shady shin": "שיידי שין",
    "shaozu": "שאוזו",
    "shinu": "שינו",
    "shiro shinobi": "שירו שינובי",
    "shoji": "שוג'י",
    "shung": "שונג",
    "shuzumu": "שוזומו",
    "shyu": "שיו",
    "skoochy": "סקוצ'י",
    "slim": "סלים",
    "smellerbee": "סמלרבי",
    "song": "סונג",
    "sozin": "סוזין",
    "sud": "סוד",
    "sung": "סונג",
    "suyin beifong": "סו-יין בייפונג",
    "swami": "סוואמי",
    "ta min": "טה מין",
    "tahno": "טאנו",
    "taliriktug": "טליריקטוג",
    "taqukaq": "טאקוקאק",
    "tarrlok": "טרלוק",
    "teo": "טיאו",
    "the boulder": "הבולדר",
    "the duke": "הדוכס",
    "the gopher": "הגופר",
    "tong": "טונג",
    "tonraq": "טונראק",
    "toza": "טוזה",
    "tu": "טו",
    "tui": "טווי",
    "tuyen": "טויין",
    "tycho": "טייכו",
    "tyro": "טיירו",
    "unalaq": "אונלק",
    "ursa": "אורסה",
    "vaatu": "ואאטו",
    "vachir": "וכיר",
    "varrick": "וריק",
    "viper": "וייפר",
    "wan": "וואן",
    "wan shi tong": "ואן שי טונג",
    "wei and wing": "ווי וווינג",
    "wen": "וון",
    "wu": "וו",
    "wu fortuneteller": "וו מגיד העתידות",
    "xin fu": "שין פו",
    "yao": "יאו",
    "yeh-lu": "יה-לו",
    "yin": "יין",
    "yon rha": "יון רהא",
    "yu": "יו",
    "yue": "יואה",
    "zei": "זיי",
    "zhao": "צאו",
}

missing = set(orig.keys()) - set(corrections.keys())
extra = set(corrections.keys()) - set(orig.keys())
print("MISSING:", missing)
print("EXTRA:", extra)

new_data = {}
for k in orig.keys():
    new_data[k] = corrections[k]

json.dump(new_data, open('/Users/abokobza/Downloads/LeaSolBok.github.io-main/actorquiz/packages/avatar/.work/data_he_new.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
print(len(new_data))
